hl.on("hyprland.start", function()
	hl.exec_cmd("uwsm app -- /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("uwsm app -- elephant")
	hl.exec_cmd("uwsm app -- walker --gapplication-service")
	hl.exec_cmd("uwsm app -- waypaper_rs --restore")
	hl.exec_cmd("uwsm app -- swaync")
	hl.exec_cmd("uwsm app -- waybar")
	hl.exec_cmd("uwsm app -- flameshot")
end)
