hl.on("hyprland.start", function()
  hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
  hl.exec_cmd("elephant")
  hl.exec_cmd("walker --gapplication-service")
  hl.exec_cmd("swaybg -i ~/Wallpapers/clouds-3.png")
  hl.exec_cmd("fcitx5")
  hl.exec_cmd("waybar")
  hl.exec_cmd("swaync")
end)
