font_family      JetBrainsMono Nerd Font Mono
font_size        12
bold_font        auto
italic_font      auto
bold_italic_font auto

cursor_shape block
cursor_blink_interval 0
background_opacity 0.9
dynamic_background_opacity yes
shell_integration no-cursor
enable_audio_bell no

window_padding_width 14
hide_window_decorations yes
confirm_os_window_close 0

input_delay 0
repaint_delay 2
sync_to_monitor no
wayland_enable_ime no

tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

mouse_map left click ungrabbed mouse_selection normal
mouse_map left doublepress ungrabbed mouse_selection word
mouse_map left triplepress ungrabbed mouse_selection line

map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard
map shift+enter send_text all \e[13;2u
map alt+shift+enter send_text all \e[13;4u

enabled_layouts splits:stack:tall:fat:grid:horizontal:vertical

map ctrl+a>c new_tab_with_cwd
map ctrl+a>h launch --location=vsplit --cwd=current
map ctrl+a>v launch --location=hsplit --cwd=current

map ctrl+a>left neighboring_window left
map ctrl+a>right neighboring_window right
map ctrl+a>up neighboring_window up
map ctrl+a>down neighboring_window down

map ctrl+a>ctrl+alt+left resize_window narrower
map ctrl+a>ctrl+alt+right resize_window wider
map ctrl+a>ctrl+alt+up resize_window taller
map ctrl+a>ctrl+alt+down resize_window shorter

map ctrl+a>space next_layout

map ctrl+a>n next_tab
map ctrl+a>p previous_tab
map ctrl+a>1 goto_tab 1
map ctrl+a>2 goto_tab 2
map ctrl+a>3 goto_tab 3
map ctrl+a>4 goto_tab 4
map ctrl+a>5 goto_tab 5

map ctrl+a>x close_window

include current-theme.conf
