exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec foot --server
exec elephant
exec walker --gapplication-service
exec fcitx5
exec wax daemon &
exec waybar
exec flameshot
exec swaync
exec while inotifywait -qq -e close_write -r ~/.config/sway/; do swaymsg reload; done
