exec uwsm app -- /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec uwsm app -- elephant
exec uwsm app -- walker --gapplication-service
exec uwsm app -- waypaper_rs --restore
exec uwsm app -- waybar --config /home/tom/dotfiles/waybar-sway/.config/waybar/config.jsonc --style /home/tom/dotfiles/waybar-sway/.config/waybar/style.css
exec uwsm app -- flameshot
exec while inotifywait -qq -e close_write -r ~/.config/sway/; do swaymsg reload; done
