### Gaps & Borders
gaps inner 4
gaps outer 8
default_border pixel 3
hide_edge_borders smart
focus_follows_mouse yes
mouse_warping container

### Layout (split horizontal por padrão - dwindle-like)

### Mouse
floating_modifier $mod normal

### Tearing
output * allow_tearing yes

### Colors (Catppuccin Mocha)
client.focused          $mauve   $surface0 $text $lavender  $lavender
client.focused_inactive $surface1 $surface0 $text $surface1  $surface1
client.unfocused        $surface1 $surface0 $text $surface1  $surface1
client.urgent           $mauve   $surface0 $text $mauve     $mauve
client.placeholder      $surface1 $surface0 $text $surface1  $surface1
client.background       $base
