### Variables
set $mod Mod4

set $term footclient
set $menu nc -U /run/user/1000/walker/walker.sock
set $browser helium-browser
set $filemanager nemo
set $zeditor zeditor
set $homedir /home/tom

### Catppuccin Mocha
set $mauve cba6f7
set $lavender b4befe
set $surface1 45475a
set $surface0 313244
set $base 1e1e2e
set $mantle 181825
set $text cdd6f4
