for_window [class="^(xdg-desktop-portal-gtk)$"] floating enable, resize set 1200 800, move position center
for_window [class="^(polkit-gnome-authentication-agent-1)$"] floating enable
for_window [app_id="walker"] focus
for_window [class="^(dota2|osu!|Lunar Client|steam_app_|gamescope)$"] fullscreen enable
